controller_manager:
  ros__parameters:
    update_rate: 200

    status_light_controller:
      type: urc_controllers/StatusLightController

    rover_drivetrain_controller:
      type: diff_drive_controller/DiffDriveController

    bms_broadcaster:
      type: urc_controllers/BMSBroadcaster

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: velocity_controllers/JointGroupVelocityController

    gripper_controller_left:
      type: position_controllers/GripperActionController

    gripper_controller_right:
      type: position_controllers/GripperActionController

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster

bms_broadcaster:
  ros__parameters:
    bms_name: battery_management
    cell_num: 6

status_light_controller:
  ros__parameters:
    status_light_name: status_light

rover_drivetrain_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel"]
    right_wheel_names: ["right_wheel"]

    wheel_separation: 0.73025
    # wheels_per_side: 1  # actually 2, but both are controlled by 1 signal
    wheel_radius: 0.12

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: base_link
    base_frame_id: base_link
    pose_covariance_diagonal: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
    twist_covariance_diagonal: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]

    open_loop: false
    enable_odom_tf: false
    position_feedback: false

    cmd_vel_timeout: 0.5
    #publish_limited_velocity: true
    #velocity_rolling_window_size: 10

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 3.0
    linear.x.min_velocity: -3.0
    linear.x.max_acceleration: 2.5
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 5.0
    angular.z.min_velocity: -5.0
    angular.z.max_acceleration: 3.0
    angular.z.min_acceleration: -3.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0

arm_controller:
  ros__parameters:
    joints:
      - shoulderjoint
      - bicepjoint
      - elbowjoint
      - wristjoint
      - clawjoint

gripper_controller_left:
  ros__parameters:
    action_monitor_rate: 20.0
    allow_stalling: false
    goal_tolerance: 0.01
    max_effort: 0.50
    stall_timeout: 1.0
    stall_velocity_threshold: 0.001
    joint: leftgripperjoint

gripper_controller_right:
  ros__parameters:
    action_monitor_rate: 20.0
    allow_stalling: false
    goal_tolerance: 0.01
    max_effort: 0.50
    stall_timeout: 1.0
    stall_velocity_threshold: 0.001
    joint: rightgripperjoint

joystick_driver:
  ros__parameters:
    max_linear_velocity_ms: 3.0
    max_angular_velocity_radians: 5.0
    joy_command_topic: /driver/joy
    cmd_vel_topic: /cmd_vel_teleop
    target_axes: [1, 3]
    invert_linear_velocity: false
    invert_angular_velocity: false
