# Controllers to test the new simulation
controller_manager:
  ros__parameters:
    update_rate: 100
  
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    position_controller:
      type: position_controllers/JointGroupPositionController

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

position_controller:
  ros_parameters:
    - FL_Swivel_Joint
    - FR_Swivel_Joint
    - BL_Swivel_Joint
    - BR_Swivel_Joint

velocity_controller:
  ros_parameters:
    - FL_Wheel_Joint
    - FR_Wheel_Joint
    - BL_Wheel_Joint
    - BR_Wheel_Joint
  

