twist_mux:
  ros_parameters:
    topics:
      navigation:
        topic: nav/cmd_vel
        timeout: 0.5
        priority: 10
      joystick: 
        topic: cmd_vel_joy
        timeout: 5.0
        priority: 20
      