arm_mjsim:
  ros__parameters:
    model_path: "/home/keseterg/Documents/RoboJackets/urc_ws/src/urc-software/urc_arm_models/urdf/walli_arm_v2_block_mjcf/walli_arm_v2_block.xml"
    fps: 100.0
    policy_rate_hz: 250.0

qp_ctrl:
  ros__parameters:
    robot_config:
      model_path: "/home/keseterg/Documents/RoboJackets/urc_ws/src/urc-software/urc_arm_models/urdf/walli_arm_v2_block_mjcf/robot.urdf"
      end_effector_frame_name: "ee_rod"
    joints:
      - base_yaw_joint
      - upper_arm_joint
      - fore_arm_joint
      - ee_roll_joint
      - ee_pitch_joint
    gains:
      base_yaw_joint:
        kp: 10.0
        kd: 5.0
        torque_limit: [-116.82, 116.82]
      upper_arm_joint:
        kp: 50.0
        kd: 10.0
        torque_limit: [-116.82, 116.82]
      fore_arm_joint:
        kp: 15.0
        kd: 1.0
        torque_limit: [-116.82, 116.82]
      ee_roll_joint:
        kp: 0.7
        kd: 0.001
        torque_limit: [-116.82, 116.82]
      ee_pitch_joint:
        kp: 0.7
        kd: 0.001
        torque_limit: [-116.82, 116.82]

controller_manager:
  ros__parameters:
    update_rate: 300 # Hz

    arm_position_controller:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_position_controller:
  ros__parameters:
    joints:
      - base_yaw_joint
      - upper_arm_joint
      - fore_arm_joint
      - ee_roll_joint
      - ee_pitch_joint
