name: Build CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    container: ros:galactic
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
          path: src/urc-software
          
      - name: Install Dependencies
        shell: bash
        run: |
          source /opt/ros/galactic/setup.bash
          sudo apt-get update
          git submodule update --init --recursive
          rosdep update --rosdistro=galactic
          rosdep install --from-paths . --ignore-src -y

      - name: Build
        shell: bash
        run: |
          source /opt/ros/galactic/setup.bash
          colcon build
